// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetSystemInfo() {
  return $Call.ByID(1347250254).then(
    /** @type {($result: any) => any} */ (
      ($result) => {
        return $$createType0($result);
      }
    ),
  );
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
  return $Call.ByID(2659711170, name);
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog(title) {
  return $Call.ByID(1188724780, title);
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog(title) {
  return $Call.ByID(4196526771, title);
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function SetTitle(title) {
  return $Call.ByID(861047163, title);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
