// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetDatabaseStatus(): $CancellablePromise<$models.DatabaseStatus> {
  return $Call.ByID(3724465559).then(($result: any) => {
    return $$createType0($result);
  });
}

export function ListGreetings(
  limit: number,
): $CancellablePromise<$models.GreetingRecord[]> {
  return $Call.ByID(384385096, limit).then(($result: any) => {
    return $$createType2($result);
  });
}

// Private type creation functions
const $$createType0 = $models.DatabaseStatus.createFrom;
const $$createType1 = $models.GreetingRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
