// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

export function OpenDirectoryDialog(
  title: string,
): $CancellablePromise<string> {
  return $Call.ByID(1467219476, title);
}

export function OpenFileDialog(title: string): $CancellablePromise<string> {
  return $Call.ByID(5797531, title);
}

export function SetTitle(title: string): $CancellablePromise<void> {
  return $Call.ByID(3089609683, title);
}
