// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DesktopService from "./desktopservice.js";
import * as GreetService from "./greetservice.js";
import * as SystemService from "./systemservice.js";
export { DesktopService, GreetService, SystemService };

export { SystemInfo } from "./models.js";
